### PR TITLE
Fix for godot 4.1

### PR DESCRIPTION
**Pull request by Infini-Creation**
I made some changes in order to have the SDK working with a recent release of Godot as well as a bunch of improvements on debug print statements to make them more useful and checking some result values before using them, preventing runtime error.

### CODE REVIEW

**Comment by ARez2** [comment]
Alright looks good to me! Thanks for your work!

**Comment by Infini-Creation** [comment]
You're welcome.

Still, I'm planning to add a lot more stuff from _LootLocker_ which may have been added/modified since you first start, but it doesn't really fit a fork and PR workflow as pretty much everything will be deeply modified.

I've already add guest login as well as a nice test scene for it, then I'll work on player a bit and leaderboard as I need them then later white label login and Steam/Google/Apple at least, also a synchronous/asynchronous mode for handle network communications. One step after another, I'll build a more and more complete SDK which will ultimately provides the same interface as _Unity_ SDK for a more straightforward conversion.

So do you wish to still be involved and keep the repo ? You could also grant me more rights (maintainer AFAIK) so I could make deeper changes without your involvement or I will eventually duplicate the repo and/or start a fresh one on my own.

Please let me know your choice.

**Comment by ARez2** [comment]
Yes Im totally fine with you being a maintainer. I currently have no need for this SDK (maybe in a later project I will) and instead of just laying around, the SDK might as well be improved.

**Comment by ARez2** [comment]
There you go. Added you

**Pull request merged**
